### ISSUE TITLE
Samantha Issue 

### ISSUE THREAD

**Issue by samrippley** [yangcheng258/DSPG_2022_GitTraining#11]
Change this line to "This is Sam" 
(https://github.com/yangcheng258/DSPG_2022_GitTraining/blob/a7a95dd7e4b3dea5c06ec2cda9e61bf6f1d9d596/yangcheng-test#L2) @yangcheng258

**Comment by yangcheng258** [comment]
https://github.com/yangcheng258/DSPG_2022_GitTraining/blob/a7a95dd7e4b3dea5c06ec2cda9e61bf6f1d9d596/yangcheng-test#L2
